# Problem 1

In [1]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin


In [2]:
import numpy as np

In [3]:
matris = np.random.randint(0,11,5)

In [6]:
matris.ndim

1

In [11]:
matris = matris.reshape(1,5,1)

In [13]:
matris.ndim

3

# Problem 2

In [30]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
odd_number = np.arange(1,10,2)
matris1 = np.random.choice(odd_number, size =(3,3))
print(matris1)

# 2 - Oluşturduğunuz matrisi parçalayın
matris2 = np.vsplit(matris1,3)
print(matris2)
x,y,z = matris2

# 3 - Parçalanmış matrisleri birleştirin
np.concatenate([x,y,z])


[[1 1 3]
 [3 7 5]
 [1 1 3]]
[array([[1, 1, 3]]), array([[3, 7, 5]]), array([[1, 1, 3]])]


array([[1, 1, 3],
       [3, 7, 5],
       [1, 1, 3]])

# Problem 3

In [32]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
nums = np.arange(5,101,2)
matris = np.random.choice(nums,size=(10,))
print(matris)
print(matris.ndim)
print(matris.shape)
print(matris.dtype)
print(matris.size)

# 2 - matris'in özelliklerini inceleyin


[85 83 23  9 43 29 39 79 11 37]
1
(10,)
int32
10
